### ISSUE TITLE
Mongoose y unique

### ISSUE THREAD

**Issue by Gabriel-LuisF** [ULL-ESIT-INF-DSI-2122/ull-esit-inf-dsi-21-22-prct12-music-api-grupo_g#1]
@esegredo 
Hemos intentado seguir las recomendaciones y colocar el atributo `unique` de mongoose en los nombres de los artistas, canciones y playlist, pero Mongodb Atlas parece no reaccionar ante este cambio y sigue permitiendonos subir dos documentos exactamente iguales.
![image](https://user-images.githubusercontent.com/65520491/169624324-c18bbe7f-3c82-4a0d-aa50-b1390e4c1acb.png)
![image](https://user-images.githubusercontent.com/65520491/169624400-eaa02f27-166d-4bd2-ad34-c57b7bf7772f.png)

**Comment by esegredo** [comment]
Borren la base de datos de MongoDB Atlas y vuelvan a probar. Puede que tengan un esquema antiguo en dicha base de datos.

Saludos.
